### ISSUE TITLE
Labe "clone" it self with open are new project in current window

### ISSUE THREAD

**Issue by Vakhrushev** [drinchev/project-label#1] opened 2017-04-25 08:46 UTC
https://i.imgur.com/YpzFfW7.png

intellij 2017.1.*

**Comment by drinchev** [comment] 2017-04-28 08:53
Seems that I can't reproduce this with my WebStorm. Anyway will check with IntelliJ CE

**Comment by tnguven** [comment] 2017-05-10 08:15
This happens when you open a new project or folder to the current one but not all the time :)

**Comment by drinchev** [comment] 2019-10-23 08:02
The Preferences dialog was added to the preferences pane, so this should've been fixed now.

**Closed as completed by drinchev** 2019-10-23 08:02 UTC
Labels: bug
